### PR TITLE
Fix several bugs.

### PR DESCRIPTION
**Pull request by gaokai320**
This pull request fixes several bugs including #51 .

1. Add `blob_sequential_idx` and `blob_sequential_bin` to fix the failure to iterate all blobs. 

2. Encode path to bytes to fix the failure to iterate all projects. 

3. Open .bin files with `rb` mode to fix the decompress error.

4. Fix the index of blob sha in .idx files.

5. Comment assignment to data property to fix `AttributeError: can't set attribute 'data'`.

6. Remove additional spaces in the return statement in `attributes` of `Commit` class.

7. Change the argument of split to bytes to successfully split bytes data.

### CODE REVIEW

**Comment by gaokai320** [comment]
The failures seem to be that the check doesn't support Python version earlier than 3.7

**Comment by user2589** [comment]
@gaokai320 I updated github workflows config to allow for Python 3.6 testing. Can you add a trivial commit to this pull request to re-trigger them?

**Important:** please use "fix:" prefix for this trivial commit.

The release action in this repo relies on commits prefixes to figure out whether a new release is necessary, what kind of version bump to do, and to populate release note.  This is explained in [How to contribute](https://ssc-oscar.github.io/oscar.py/contribute.html#how-to-contribute), more to read about conventional commits [here](https://www.conventionalcommits.org/en/v1.0.0/). Right now, the only commit in this pull request won't trigger anything - this "fix" prefix on the dummy commit will fix that for now.

**Comment by gaokai320** [comment]
Done. But it still requires manual approval to run the workflow for outside contributors.

**Comment by user2589** [comment]
@audrism if you don't mind I'm going to remove the requirement for approval.

Originally unit tests were to be executed on WoC servers, which carried some security risks. With the current implementation, unit tests are run on a toy dataset included in the repository and are completely contained in test environment. Thus, the initial approval requirement doesn't make a lot of sense anymore.

**Comment by user2589** [comment]
@audrism my bad - there is no option to skip manual approval entirely. Currently it is required for first time contributors only, which isn't that bad - I'm leaving it as is.

**Pull request merged**
