### PR TITLE
fix: bump version to 1.1.3

### PR DESCRIPTION
**Pull request by audrism**

### CODE REVIEW

**Comment by user2589** [comment]
There is no need to bump version - it will be done automatically. 
- only fix commits: minor revision (bump the last number)
- new features: major revision (bump the second number)
- breaking changes: new version (the first number)

**Comment by audrism** [comment]
- Just did it to verify that the pypi did not appear to get the latest data:
    https://pypi.org/project/oscar/ shows 1.1.0
- since a bunch of new relations were added, perhaps it should be 1.2.0 now?

**Comment by user2589** [comment]
It did not pass tests (red cross in front of the commit) so it did not publish a new version. The same happened last time, too. I'm going to check Travis log to see what happened

**Comment by audrism** [comment]
@dkennard3 @atutko2 does the current version build on our servers? If not, can it be made to pass all the tests?
Once it it passes the tests the version number should be bumped up to 1.2.0 since there are many new relations added. 
Also: new feature pull request needs to be submitted outlining the changes (travis builds/deploys to pypi after such PR is merged)

**Comment by user2589** [comment]
The problem is with the release script. I'll fix it.
To indicate a new feature, commit message should be prepended with a "feat:". Breaking changes prefix is "BREAKING CHANGE:". Full reference can be found here: https://www.conventionalcommits.org/

**Comment by audrism** [comment]
Thank you!

**Pull request merged**
